### ISSUE TITLE
Synchronous mode crashes the provided training script

### ISSUE THREAD

**Issue by the-big-bad-wolf** [angelomorgado/CARLA-GymDrive#10]
After #8 the example_sb3_dqn_training.py script crashes when running with synchronous mode enabled. I don't think the patch is erroneous, but rather that before #8 synchronous mode never was enabled because it got reset to False once you loaded a map and the original setting wasn't reapplied. I verified this prior to creating #8 by printing the world settings after loading a map, which showed that synchronous mode was not turned on.

The script crashes in get_data() for the GNSS class in sensors.py with the error message "AttributeError: 'NoneType' object has no attribute 'latitude'"

**Comment by angelomorgado** [comment]
I don't think that's the case but I won't remove all the cards on the table. Now i won't be able to look at the problem, but monday I'll focus on fixing those problems once and for all. Is that ok?

**Comment by angelomorgado** [comment]
Fixed the synchronization with the sensors! Do a git pull or clone and try it out!

**Comment by the-big-bad-wolf** [comment]
It works!
