### ISSUE TITLE
Steering-jerk reward function doesn't work for continuous control 

### ISSUE THREAD

**Issue by the-big-bad-wolf** [angelomorgado/CARLA-GymDrive#11]
The reason is that self.__steering_angle isn't updated in the continuous control_vehicle() function in vehicle.py, so it is always 0.

**Comment by angelomorgado** [comment]
You're totally right! Since I wasn't using that reward function in my personal project i didn't really notice that, thank you so much for noticing. And if you find any more mistakes please let me know, i'll patch it ASAP.
