### ISSUE TITLE
Map is briefly rendered upon map change even if no_rendering_mode is set to true

### ISSUE THREAD

**Issue by the-big-bad-wolf** [angelomorgado/CARLA-GymDrive#7]
Because the world loads the default settings upon changing map, the map is briefly rendered before the no_rendering_mode is reapplied. This uses a lot of resources in my experience. The fix is easy as there is an option to not reset settings upon loading a new world with client.load_world()

**Comment by angelomorgado** [comment]
Hey there, it seems that the no render mode is being a nuisance. When I developed the framework i never really had it in mind because most projects need the rendering aspect, so that's my bad. Thanks for the pull request, i'll review it, and if everything is cool, i'll definetly accept it!
